/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.dataModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dm.dataModel.Relationship#getType <em>Type</em>}</li>
 *   <li>{@link eu.jgen.notes.dm.dataModel.Relationship#getTarget <em>Target</em>}</li>
 *   <li>{@link eu.jgen.notes.dm.dataModel.Relationship#getRelname <em>Relname</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dm.dataModel.DataModelPackage#getRelationship()
 * @model
 * @generated
 */
public interface Relationship extends EntityFeature
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see eu.jgen.notes.dm.dataModel.DataModelPackage#getRelationship_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dm.dataModel.Relationship#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(Entity)
   * @see eu.jgen.notes.dm.dataModel.DataModelPackage#getRelationship_Target()
   * @model
   * @generated
   */
  Entity getTarget();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dm.dataModel.Relationship#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Entity value);

  /**
   * Returns the value of the '<em><b>Relname</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relname</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relname</em>' reference.
   * @see #setRelname(Relationship)
   * @see eu.jgen.notes.dm.dataModel.DataModelPackage#getRelationship_Relname()
   * @model
   * @generated
   */
  Relationship getRelname();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dm.dataModel.Relationship#getRelname <em>Relname</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relname</em>' reference.
   * @see #getRelname()
   * @generated
   */
  void setRelname(Relationship value);

} // Relationship
