/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DataModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("eu/jgen/notes/dm/parser/antlr/internal/InternalDataModel.tokens");
	}
}
