/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.parser.antlr;

import com.google.inject.Inject;
import eu.jgen.notes.dm.parser.antlr.internal.InternalDataModelParser;
import eu.jgen.notes.dm.services.DataModelGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DataModelParser extends AbstractAntlrParser {

	@Inject
	private DataModelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDataModelParser createParser(XtextTokenStream stream) {
		return new InternalDataModelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DataModel";
	}

	public DataModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DataModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
