/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm;

import eu.jgen.notes.dm.AbstractDataModelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DataModelRuntimeModule extends AbstractDataModelRuntimeModule {
}
