/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm;

import eu.jgen.notes.dm.DataModelStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DataModelStandaloneSetup extends DataModelStandaloneSetupGenerated {
  public static void doSetup() {
    new DataModelStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
