/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public abstract class AbstractDataModelScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
