/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class DataModelLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public DataModelLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
