/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DataModelStandaloneSetup extends DataModelStandaloneSetupGenerated {

	def static void doSetup() {
		new DataModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
