/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DataModelRuntimeModule extends AbstractDataModelRuntimeModule {
}
