/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.jgen.notes.dm.DataModelRuntimeModule;
import eu.jgen.notes.dm.DataModelStandaloneSetup;
import eu.jgen.notes.dm.ide.DataModelIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DataModelIdeSetup extends DataModelStandaloneSetup {
  @Override
  public Injector createInjector() {
    DataModelRuntimeModule _dataModelRuntimeModule = new DataModelRuntimeModule();
    DataModelIdeModule _dataModelIdeModule = new DataModelIdeModule();
    return Guice.createInjector(Modules2.mixin(_dataModelRuntimeModule, _dataModelIdeModule));
  }
}
