/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.ide;

import eu.jgen.notes.dm.ide.AbstractDataModelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DataModelIdeModule extends AbstractDataModelIdeModule {
}
