/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.ui;

import com.google.inject.Injector;
import eu.jgen.notes.dm.ui.internal.DmActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DataModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DmActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DmActivator.getInstance().getInjector(DmActivator.EU_JGEN_NOTES_DM_DATAMODEL);
	}
	
}
