/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.validation;

import eu.jgen.notes.dm.validation.AbstractDataModelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DataModelValidator extends AbstractDataModelValidator {
}
