/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.ui;

import eu.jgen.notes.dm.ui.AbstractDataModelUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DataModelUiModule extends AbstractDataModelUiModule {
  public DataModelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
