/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.ui.tests;

import com.google.inject.Injector;
import eu.jgen.notes.dm.ui.internal.DmActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DataModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DmActivator.getInstance().getInjector("eu.jgen.notes.dm.DataModel");
	}

}
