/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dm.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DataModelUiModule extends AbstractDataModelUiModule {
}
